accounting/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from . import views
from . import api


# router = routers.DefaultRouter()
# router.register(r'invoice', api.InvoiceViewSet, basename='invoice')

app_name = 'accounting'

invoice_list = api.InvoiceViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

invoice_detail = api.InvoiceViewSet.as_view({
    'get': 'retrieve',
    'post': 'update',
    'put': 'update'
})

bill_list = api.BillViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

bill_detail = api.BillViewSet.as_view({
    'get': 'retrieve',
    'post': 'update',
    'put': 'update'
})

urlpatterns = [
      path('', views.index, name='index'),
      path('clients', views.clients, name='clients'),
      path('vendors', views.vendors, name='vendors'),

      path('company/create', views.company_create, name='company_create'),

      path('items', views.items, name='items'),

      path('invoices', views.invoices, name='invoices'),
      path('invoices/<uuid:uuid>', views.invoice, name='invoice'),
      path('invoice/<uuid:uuid>', views.public_invoice, name='invoice'),

      path('bills', views.bills, name='bills'),
      path('bills/<uuid:uuid>', views.bill, name='bill'),

      path('api/v1/rest-auth/', include('rest_auth.urls')),

      path('api/v1/invoice', invoice_list, name='invoice-list'),
      path('api/v1/invoice/<uuid:uuid>', invoice_detail, name='invoice-detail'),
      path('api/public/invoice/<uuid:uuid>', api.PublicInvoice.as_view(), name='invoice-public'),
      path('api/v1/invoice/<uuid:uuid>/<uuid:item>', invoice_detail, name='invoice-detail'),

      path('api/v1/bill', bill_list, name='bill-list'),
      path('api/v1/bill/<uuid:uuid>', bill_detail, name='bill-detail'),
      path('api/v1/bill/<uuid:uuid>/<uuid:item>', bill_detail, name='bill-detail'),

      path('api/v1/item', api.ItemViewSet.as_view({'get': 'list', 'post': 'create'}), name='item-api'),
      path('api/v1/item/<uuid:uuid>', api.ItemViewSet.as_view({'put': 'update'}), name='item-api'),

      path('api/v1/client', api.ClientViewSet.as_view({'get': 'list', 'post': 'create'}), name='clients-api'),
      path('api/v1/client/<uuid:uuid>', api.ClientViewSet.as_view({'put': 'update'}), name='clients-api'),

      path('api/v1/vendor', api.VendorViewSet.as_view({'get': 'list', 'post': 'create'}), name='vendors-api'),
      path('api/v1/vendor/<uuid:uuid>', api.VendorViewSet.as_view({'put': 'update'}), name='vendors-api'),

      path('api/public/currency', api.CurrencyView.as_view(), name='currency-api'),

  ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += router.urls

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounting.urls')),
    path('accounts/', include('login.urls')),
    # path('', include('drfpasswordless.urls')),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_up/2', views.sign_up_two, name='sign_up_two'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
]

accounting/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import date
import uuid


class Currency(models.Model):
    name = models.CharField(max_length=20)
    code = models.CharField(max_length=3)


class Company(models.Model):
    name = models.CharField(max_length=255)
    default_currency = models.ForeignKey(Currency, on_delete=models.PROTECT, default=1)


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)


class CompanyDetail(models.Model):
    company = models.OneToOneField(Company, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    zip = models.CharField(max_length=8)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    vat = models.CharField(max_length=200)
    commerce = models.CharField(max_length=200)
    logo = models.IntegerField()


class BankAccount(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    start_amount = models.IntegerField()
    name = models.CharField(max_length=200)
    iban = models.CharField(max_length=34)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)


class Client(models.Model):
    name = models.CharField(max_length=255)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    company = models.ForeignKey(Company, related_name='client_details', on_delete=models.PROTECT)


class ClientDetail(models.Model):
    client = models.OneToOneField(Client, related_name='details', on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    zip = models.CharField(max_length=8)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    vat = models.CharField(max_length=200)
    commerce = models.CharField(max_length=200)


class ClientAccount(models.Model):
    client = models.OneToOneField(Client, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Invoice(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    reference = models.CharField(max_length=35)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)


class Item(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    description = models.TextField()
    default_price = models.DecimalField(decimal_places=2, max_digits=20)
    company = models.ForeignKey(Company, on_delete=models.PROTECT)


class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, related_name='items', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name='invoice_item_item', on_delete=models.PROTECT)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    amount = models.IntegerField()


class InvoiceViewed(models.Model):
    invoice = models.OneToOneField(Invoice, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)


class InvoicePaid(models.Model):
    invoice = models.OneToOneField(Invoice, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)


class InvoiceSent(models.Model):
    invoice = models.OneToOneField(Invoice, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)


class Vendor(models.Model):
    name = models.CharField(max_length=255)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    company = models.ForeignKey(Company, related_name='vendor_details', on_delete=models.PROTECT)


class VendorDetail(models.Model):
    vendor = models.OneToOneField(Vendor, related_name='details', on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    zip = models.CharField(max_length=8)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    vat = models.CharField(max_length=200)
    commerce = models.CharField(max_length=200)


class Bill(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT)
    date = models.DateField(default=date.today)
    reference = models.CharField(max_length=35)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)


class BillItem(models.Model):
    bill = models.ForeignKey(Bill, related_name='items', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name='bill_item_item', on_delete=models.PROTECT)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    amount = models.IntegerField()

accounting/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import Currency, Client, Vendor, Company, CompanyDetail, Employee, Item
from .decorators import employee_check
from .tasks import send_email_invoice

from login.decorators import profile_completed


@login_required()
@profile_completed
def index(request):
    return render(request, 'accounting/index.html')


# Client
@login_required()
@employee_check
@profile_completed
def clients(request):
    return render(request, 'accounting/clients.html')


# Vendors
@login_required()
@employee_check
@profile_completed
def vendors(request):
    return render(request, 'accounting/vendors.html')


# Company
@login_required()
@profile_completed
def company_create(request):
    if request.method == "GET":
        if hasattr(request.user, 'employee'):
            messages.add_message(request, messages.INFO, F"You already have a company.")
            return HttpResponseRedirect(reverse('accounting:clients'))
        return render(request, 'accounting/company_create.html')

    if not request.method == "POST":
        return HttpResponse("Method not allowed", status=405)

    with transaction.atomic():
        Company.objects.create(
            name=request.POST['name'],
        )
        company = Company.objects.latest('id')
        CompanyDetail.objects.create(
            company=company,
            address=request.POST['address'],
            zip=request.POST['zip'],
            city=request.POST['city'],
            country=request.POST['country'],
            email=request.POST['email'],
            phone=request.POST['phone'],
            vat=request.POST['vat'],
            commerce=request.POST['commerce'],
            logo=0
        )
        Employee.objects.create(
            company=company,
            user=request.user
        )

    messages.add_message(request, messages.SUCCESS, F"Created company.")
    return HttpResponseRedirect(reverse('accounting:clients'))


# Item
@login_required()
@employee_check
@profile_completed
def items(request):
    return render(request, 'accounting/items.html')


# Invoice
@login_required()
@employee_check
@profile_completed
def invoices(request):
    return render(request, 'accounting/invoices.html')


@login_required()
@employee_check
@profile_completed
def invoice(request, uuid):
    context = {
        'uuid': uuid
    }
    return render(request, 'accounting/invoice.html', context)


def public_invoice(request, uuid):
    context = {
        'uuid': uuid
    }
    return render(request, 'public_accounting/invoice.html', context)


# Bill
@login_required()
@employee_check
@profile_completed
def bills(request):
    return render(request, 'accounting/bills.html')


@login_required()
@employee_check
@profile_completed
def bill(request, uuid):
    context = {
        'uuid': uuid
    }
    return render(request, 'accounting/bill.html', context)

accounting/templates/accounting/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Accounting - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "library/choices/choices.css" %}">
    <link rel="stylesheet" href="{% static "library/simple-datatables/simple-datatables.css" %}">
    <link rel="stylesheet" href="{% static "css/accounting.css" %}">
</head>
<body>
<nav>
    <ul>
        <li>
            <a href="{% url 'login:logout' %}">Log out</a>
        </li>
    </ul>
</nav>
<ul class="messages" data-messages>
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </li>
    {% endfor %}
</ul>

<div class="page">
<aside>
    <ul>
        <li>
            <a href="{% url 'accounting:index' %}">Dashboard</a>
        </li>

        <li>Relations
            <ul>
                <li>
                    <a href="{% url 'accounting:clients' %}">Clients</a>
                </li>
                <li>
                    <a href="{% url 'accounting:vendors' %}">Vendors</a>
                </li>
            </ul>
        </li>

        <li>Transaction
            <ul>
                <li>
                    <a href="{% url "accounting:invoices" %}">Invoices</a>
                </li>
                <li>
                    <a href="{% url "accounting:bills" %}">Bills</a>
                </li>
            </ul>
        </li>

        <li>Administration
            <ul>
                <li>
                    <a href="">Account</a>
                </li>
                <li>
                    <a href="">Company</a>
                </li>
                <li>
                    <a href="">Banking</a>
                </li>
                <li>
                    <a href="{% url "accounting:items" %}">Items</a>
                </li>
            </ul>
        </li>
    </ul>
</aside>

<main>
    {% block content %}
    {% endblock %}
</main>
</div>

<script src="{% static "library/choices/choices.js" %}"></script>
<script src="{% static "library/simple-datatables/simple-datatables.js" %}"></script>
<script src="{% static "js/app.js" %}"></script>
{% block scripts %}
{% endblock %}

</body>
</html>

accounting/templates/accounting/bill.html
{% extends "accounting/base.html" %}

{% block title %}
    Bills
{% endblock %}


{% block content %}
{#data-update-item-url="{% url 'accounting:bill-item' %}"#}
    <table data-table data-url="{% url 'accounting:bill-detail' uuid %}"  data-row-link-base="#">
    </table>
    <table data-table data-table-items data-url="{% url 'accounting:bill-detail' uuid %}" data-row-link-base="#">
    </table>

    <section data-update-form>
        <h2>Add item</h2>
        <span data-url="{% url 'accounting:bill-detail' uuid %}"></span>
        {% csrf_token %}
        <select data-item-pk data-choices data-url="{% url 'accounting:item-api' %}">
            <option value="">Select item</option>
            {% for item in items %}
                <option value="{{ item.uuid }}" data-price="{{ item.default_price }}">
                    {{ item.description }}
                </option>
            {% endfor %}
        </select>
        <input data-field type="number" name="amount" placeholder="Amount">
        <input data-field type="number" name="price" placeholder="price">
        <button data-submit>Add item</button>
    </section>

{% endblock %}

accounting/templates/accounting/bills.html
{% extends "accounting/base.html" %}

{% block title %}
    Bills
{% endblock %}


{% block content %}

    <table data-table data-url="{% url 'accounting:bill-list' %}" data-row-link-base="{{ request.get_full_path }}">
    </table>

    <section data-create-form>
        <h2>Create bill</h2>
        <span data-url="{% url 'accounting:bill-list' %}"></span>
        {% csrf_token %}
        <input data-field type="text" name="date" placeholder="Date">
        <select data-field data-choices name="vendor" data-url="{% url 'accounting:vendors-api' %}">
            <option value="">Select vendor</option>
        </select>
        <input data-field type="text" name="reference" placeholder="reference">
        <select data-field name="currency" data-choices data-url="{% url 'accounting:currency-api' %}">
        </select>
        <div data-subs>
            <div data-sub-row class="row">
                <select data-item-pk data-choices data-url="{% url 'accounting:item-api' %}">
                    <option value="">Select item</option>
                </select>
                <input data-sub-item-field type="number" name="amount" placeholder="Amount">
                <input data-sub-item-field type="number" name="price" placeholder="price">
            </div>
        </div>
        <button data-add-sub-row class="add">Add item</button>
        <template data-sub-template>
            <div data-sub-row class="row">
                <select data-item-pk data-choices data-url="{% url 'accounting:item-api' %}">
                    <option value="">Select item</option>
                </select>
                <input data-sub-item-field type="number" name="amount" placeholder="Amount">
                <input data-sub-item-field type="number" name="price" placeholder="price">
            </div>
        </template>
        <button data-submit>Create</button>
    </section>
{% endblock %}

accounting/templates/accounting/client.html
{% extends "accounting/base.html" %}
{% load static %}

{% block title %}
    {{ client.name }}
{% endblock %}


{% block content %}
    <span data-update-url="{% url 'accounting:clients-api' client.uuid %}"></span>
    <input data-auto-update value="{{ client.name }}" name="name" placeholder="Name"/>
    <input data-auto-update value="{{ client.address }}" name="address" placeholder="Address"/>
    <input data-auto-update value="{{ client.zip }}" name="zip" placeholder="Zip"/>
    <input data-auto-update value="{{ client.city }}" name="city" placeholder="City"/>
    <input data-auto-update value="{{ client.country }}" name="country" placeholder="Country"/>
    <input data-auto-update value="{{ client.email }}" name="email" placeholder="Email"/>
    <input data-auto-update value="{{ client.phone }}" name="phone" placeholder="Phone"/>
    <input data-auto-update value="{{ client.vat }}" name="vat" placeholder="Vat-ID"/>
    <input data-auto-update value="{{ client.commerce }}" name="commerce" placeholder="Commerce-ID"/>
{% endblock %}

{% block scripts %}
    <script src="{% static "js/client.js" %}"></script>
{% endblock %}

accounting/templates/accounting/clients.html
{% extends "accounting/base.html" %}

{% block title %}
    Clients
{% endblock %}


{% block content %}
    <table data-table data-url="{% url 'accounting:clients-api' %}" data-row-link-base="#">
    </table>

    <section data-create-form>
        <h2>Create client</h2>

        <span data-url="{% url 'accounting:clients-api' %}"></span>
        <input data-field type="text" name="name" placeholder="Name">
        <div data-sub-row>
            <input data-sub-field type="text" name="address" placeholder="Address">
            <input data-sub-field type="text" name="zip" placeholder="Zip">
            <input data-sub-field type="text" name="city" placeholder="City">
            <input data-sub-field type="text" name="country" placeholder="Country">
            <input data-sub-field type="text" name="email" placeholder="Email">
            <input data-sub-field type="text" name="phone" placeholder="Phone">
            <input data-sub-field type="text" name="vat" placeholder="VAT-ID">
            <input data-sub-field type="text" name="commerce" placeholder="Commerce ID">
        </div>
        <button data-submit>Create</button>
    </section>
{% endblock %}

accounting/templates/accounting/company_create.html
{% extends "accounting/base.html" %}

{% block title %}
    Create company
{% endblock %}


{% block content %}
    <section>
        <h2>Create your company</h2>
        <p>We need this information to proceed</p>

        <form method="POST" action="{% url 'accounting:company_create' %}">
            {% csrf_token %}
            <input type="text" name="name" placeholder="Name">
            <input type="text" name="address" placeholder="Address">
            <input type="text" name="zip" placeholder="Zip">
            <input type="text" name="city" placeholder="City">
            <input type="text" name="country" placeholder="Country">
            <input type="text" name="email" placeholder="Email">
            <input type="text" name="phone" placeholder="Phone">
            <input type="text" name="vat" placeholder="VAT-ID">
            <input type="text" name="commerce" placeholder="Commerce ID">
            <button>Create</button>
        </form>
    </section>
{% endblock %}

accounting/templates/accounting/index.html
{% extends "accounting/base.html" %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    <section>
        <h1>Welcome to Django CRM</h1>
        <p>Use the side menu to navigate through all pages.</p>
    </section>
{% endblock %}

accounting/templates/accounting/invoice.html
{% extends "accounting/base.html" %}

{% block title %}
    Invoices
{% endblock %}


{% block content %}
    <table data-table data-url="{% url 'accounting:invoice-detail' uuid %}" data-row-link-base="#">
    </table>
    <table data-table data-table-items data-url="{% url 'accounting:invoice-detail' uuid %}" data-row-link-base="#">
    </table>

    <section data-update-form>
        <span data-url="{% url 'accounting:invoice-detail' uuid %}"></span>
        <h2>Add item</h2>
        <select data-item-pk data-choices data-url="{% url 'accounting:item-api' %}">
            <option value="">Select item</option>
            {% for item in items %}
                <option value="{{ item.uuid }}" data-price="{{ item.default_price }}">
                    {{ item.description }}
                </option>
            {% endfor %}
        </select>
        <input data-field type="number" name="amount" placeholder="Amount">
        <input data-field type="number" name="price" placeholder="price">
        <button data-submit>Add item</button>
    </section>
{% endblock %}

accounting/templates/accounting/invoices.html
{% extends "accounting/base.html" %}

{% block title %}
    Invoices
{% endblock %}


{% block content %}

    <table data-table data-url="{% url 'accounting:invoice-list' %}" data-row-link-base="{{ request.get_full_path }}">
    </table>

    <section data-create-form>
        <h2>Create invoice</h2>
        <span data-url="{% url 'accounting:invoice-list' %}"></span>
        {% csrf_token %}
        <select data-field data-choices name="client" data-url="{% url 'accounting:clients-api' %}">
            <option value="">Select client</option>
        </select>
        <input data-field type="text" name="reference" placeholder="reference">
        <select data-field name="currency" data-choices data-url="{% url 'accounting:currency-api' %}">
        </select>
        <div data-subs>
            <div data-sub-row class="row">
                <select data-item-pk data-choices data-url="{% url 'accounting:item-api' %}">
                    <option value="">Select item</option>
                </select>
                <input data-sub-item-field type="number" name="amount" placeholder="Amount">
                <input data-sub-item-field type="number" name="price" placeholder="price">
            </div>
        </div>
        <button data-add-sub-row class="add">Add item</button>
        <template data-sub-template>
            <div data-sub-row class="row">
                <select data-item-pk data-choices data-url="{% url 'accounting:item-api' %}">
                    <option value="">Select item</option>
                </select>
                <input data-sub-item-field type="number" name="amount" placeholder="Amount">
                <input data-sub-item-field type="number" name="price" placeholder="price">
            </div>
        </template>
        <button data-submit>Create</button>
    </section>
{% endblock %}

accounting/templates/accounting/items.html
{% extends "accounting/base.html" %}
{% load static %}

{% block title %}
    Items
{% endblock %}

{% block content %}
    <table data-table data-url="{% url 'accounting:item-api' %}" data-row-link-base="#">
    </table>

    <section data-create-form>
        <h2>Create item</h2>
        <span data-url="{% url 'accounting:item-api' %}"></span>
        <input data-field type="text" name="description" placeholder="Description">
        <input data-field type="number" name="default_price" placeholder="Default price">
        <button data-submit>Create</button>
    </section>
{% endblock %}

accounting/templates/accounting/vendors.html
{% extends "accounting/base.html" %}

{% block title %}
    Vendors
{% endblock %}


{% block content %}
    <table data-table data-url="{% url 'accounting:vendors-api' %}" data-row-link-base="#">
    </table>

    <section data-create-form>
        <h2>Create Vendor</h2>
        <span data-url="{% url 'accounting:vendors-api' %}"></span>
        <input data-field type="text" name="name" placeholder="Name">
        <div data-sub-row>
            <input data-sub-field type="text" name="address" placeholder="Address">
            <input data-sub-field type="text" name="zip" placeholder="Zip">
            <input data-sub-field type="text" name="city" placeholder="City">
            <input data-sub-field type="text" name="country" placeholder="Country">
            <input data-sub-field type="text" name="email" placeholder="Email">
            <input data-sub-field type="text" name="phone" placeholder="Phone">
            <input data-sub-field type="text" name="vat" placeholder="VAT-ID">
            <input data-sub-field type="text" name="commerce" placeholder="Commerce ID">
        </div>
        <button data-submit>Create</button>
    </section>
{% endblock %}